common:
    message: Hi from sipment-service.properties file
enableSwagger: true
logger: local
management:
    endpoint:
        health:
            show-details: always
        loggers:
            enabled: true
    endpoints:
        web:
            exposure:
                include: loggers, health
    health:
        circuitbreakers:
            enabled: true
    tracing:
        sampling:
            probability: 1.0
    zipkin:
        tracing:
            endpoint: http://localhost:9411/api/v2/spans
microservice-one:
    value: 100
resilience4j:
    circuitbreaker:
        instances:
            dashboardCount:
                wait-duration-in-open-state: 5s
				automatic-transition-from-open-to-half-open-enabled: true
				event-consumer-buffer-size: 10
				register-health-indicator: true
				permitted-number-of-calls-in-half-open-state: 3
				sliding-window-type: count-based
				minimum-number-of-calls: 3
				failure-rate-threshold: 50
				sliding-window-size: 10
server:
    port: 9070
    servlet:
        context-path: /shipment-service
shipment:
    export:
        contextRoute: http://localhost:9070/shipment-service
shipment-service:
    driver-class-name: oracle.jdbc.OracleDriver
    jdbcUrl: ${shipment-service.url}
    password: ORdr#08122020_UL#rep
    url: jdbc:oracle:thin:@d00ts7_tpurgent?TNS_ADMIN=src/main/resources/Wallet_D00TS7_ATP_QA_New
    username: WIMTREPT
spring:
    datasource:
        hikari:
            connectionTimeout: 30000
            idleTimeout: 30000
            maxLifetime: 2000000
            maximumPoolSize: 20
            minimumIdle: 5
            poolName: SpringBootJPAHikariCP
    jpa:
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                use_sql_comments: true
    mail:
        debug: true
        host: smtp.gmail.com
        password: sjqijumpukzfxtgt
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    auth.login.disable: true
                    starttls:
                        enable: true
                        required: false
        username: balaramrhs.friend@gmail.com
    main:
        allow-circular-references: true
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 500MB
user-service:
    ribbon:
        listOfServers: https://unlv-digi-log-test-oci.opc.oracleoutsourcing.com/
